name: albertoguaman
description: "Portafolio multiplataforma"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.3.1
  url_strategy: ^0.2.0
  universal_html: ^2.2.4
  firebase_core: ^3.1.1
  flutter_launcher_icons: ^0.13.1
  intl: ^0.19.0
  provider: ^6.1.2
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  flutter_staggered_grid_view: ^0.7.0
  http: ^1.2.2
  html: ^0.15.5
  flutter_animate: ^4.5.2
  animated_text_kit: ^4.2.2
  responsive_grid_list: ^1.4.0
  responsive_layout_grid: ^1.1.2
  animated_background: ^2.0.0
  zwidget: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/img/mause_cick.png"
  web:
    generate: true
    image_path: "assets/img/mause_cick.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/img/
    - assets/img/project/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Minecraftia
      fonts:
        - asset: assets/fonts/minecraft_font.ttf

    - family: Alegreya
      fonts:
        - asset: assets/fonts/Alegreya/static/Alegreya-Regular.ttf