List<Map<String, dynamic>> dataList = [
  {
    'title': 'Tinguar ',
    'country': 'Ecuador ',
    'proyect': 'Generador de link',
    'skill': 'Flutter, Dart, Firebase',
    'jobs': 'Freelancer',
    'link': 'https://tiendas.tinguar.com/',
  },
  {
    'title': 'Sciedtec ',
    'country': 'Ecuador ',
    'proyect': 'Pagina web',
    'skill': 'Js, Css, Wordpress',
    'jobs': 'Contrato',
    'link': 'https://sciedtec.com/',
  },
  {
    'title': 'N/A ',
    'country': 'Ecuador ',
    'proyect': 'Alimentacion Saludable',
    'skill': 'Flutter, Dart, SqLite',
    'jobs': 'Freelancer',
    'link': 'https://itsjapon.edu.ec/apps/',
  },
  {
    'title': 'N/A ',
    'country': 'Ecuador ',
    'proyect': 'Portafolio',
    'skill': 'Flutter, Dart',
    'jobs': 'Propio',
    'link': 'https://albertoguaman.com',
  },
  {
    'title': 'All Clean Ways ',
    'country': 'Estados Unidos ',
    'proyect': 'Diseño Web - CMS',
    'skill': 'Js, Css, Wordpress',
    'jobs': 'Freelancer',
    'link': 'https://allcleanways.com/',
  },
  {
    'title': 'Inox Hierro ',
    'country': 'Ecuador ',
    'proyect': 'Diseño Web - CMS',
    'skill': 'Js, Css, Wordpress',
    'jobs': 'Freelancer',
    'link': 'https://inoxhierroec.com/',
  },
  {
    'title': 'Arminox ',
    'country': 'Ecuador ',
    'proyect': 'Diseño Web - CMS',
    'skill': 'Js, Css, Wordpress',
    'jobs': 'Freelancer',
    'link': 'https://arminoxec.com/',
  },
  {
    'title': 'Lars Tree Service ',
    'country': 'Estados Unidos ',
    'proyect': 'Diseño Web - CMS',
    'skill': 'Js, Css, Wordpress',
    'jobs': 'Freelancer',
    'link': 'https://larstreeservice.com/',
  }
];