// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL6_CuIfhPQeYl6oHsJvHpmxrVpF41d5c',
    appId: '1:756264995890:web:194d6e6828b82fc789402b',
    messagingSenderId: '756264995890',
    projectId: 'alberto-guaman-dev',
    authDomain: 'alberto-guaman-dev.firebaseapp.com',
    storageBucket: 'alberto-guaman-dev.appspot.com',
    measurementId: 'G-BPC7JT2RGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBcUvTbIlMcsAEhIbWWMtaxmOPaFK4MpI',
    appId: '1:756264995890:android:d21f6c42d805f9d589402b',
    messagingSenderId: '756264995890',
    projectId: 'alberto-guaman-dev',
    storageBucket: 'alberto-guaman-dev.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL6_CuIfhPQeYl6oHsJvHpmxrVpF41d5c',
    appId: '1:756264995890:web:298b513bc4dc8c1489402b',
    messagingSenderId: '756264995890',
    projectId: 'alberto-guaman-dev',
    authDomain: 'alberto-guaman-dev.firebaseapp.com',
    storageBucket: 'alberto-guaman-dev.appspot.com',
    measurementId: 'G-5ZLBMED1WY',
  );
}
